<?php

namespace getInvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    
        public function getAllCompaniesByUserId($user) {
               
        $em = $this->getEntityManager();

        $query = $em->createQuery(
                "SELECT p FROM getInvoiceBundle:Company p WHERE p.user = :user ORDER BY p.name ASC");
        $query->setParameter('user', $user);
        return $query->getResult();
    }
}
