<?php

namespace getInvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository {

    public function getAllCustomersByCompanyId($company) {

        $em = $this->getEntityManager();

        $query = $em->createQuery(
                "SELECT p FROM getInvoiceBundle:Customer p WHERE p.company_id = :company ORDER BY p.name ASC");
        $query->setParameter('company', $company);
        return $query->getResult();
    }

    public function getAllCustomersByUserId($user) {

        $em = $this->getEntityManager();

        $query = $em->createQuery(
                "SELECT p FROM getInvoiceBundle:Customer p WHERE p.user = :user ORDER BY p.name ASC");
        $query->setParameter('user', $user);
        return $query->getResult();
    }

}
