<?php

namespace getInvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository {

    public function getAllInvoicesByIssueDateAscending($user) {

        $em = $this->getEntityManager();

        $query = $em->createQuery(
                "SELECT p FROM getInvoiceBundle:Invoice p JOIN getInvoiceBundle:Customer b WHERE b.user = :user ORDER BY p.id ASC");
        $query->setParameter('user', $user);
        return $query->getResult();
    }

    public function getAllVatInvoices() {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(
              //  "SELECT p FROM getInvoiceBundle:Invoice p JOIN getInvoiceBundle:InvoiceCorrective b WHERE p.id <> b.invoices");
              "SELECT u FROM getInvoiceBundle:Invoice u WHERE u.id = :id");
   
        $query->setParameter('id', 2);
        return $query->getResult();
    }
    
    public function getSelectedInvoices() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $selectedInvoices = $qb
                ->select('u')
                ->from('getInvoiceBundle:Invoice', 'u')
                ->where('u.id = :id')
                ->setParameter('id', 1)
                ->getQuery();
        return $selectedInvoices;        
    }

}
