<?php

namespace getInvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
        public function getAllInvoicesByIssueDateAscending($user) {
        
        $em = $this->getEntityManager();
        
        $query = $em->createQuery(
                "SELECT p FROM getInvoiceBundle:Invoice");
    }

}
