<?php

namespace getInvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceCorrectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceCorrectiveRepository extends EntityRepository
{
}
