get_invoice:
    resource: "@getInvoiceBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

invoice_folder:
    defaults: { _controller: getInvoiceBundle:Invoice:pdf }
    path: /pdf