# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.logo_uploader:
        class: getInvoiceBundle\FileUploader
        arguments: ['%Logo_directory%']
    app.doctrine_brochure_listener:
        class: getInvoiceBundle\EventListener\LogoUploadListener
        arguments: ['@app.logo_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }        
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
